package:
  name: queuedWriters
  version: 0.0.1

source:
  git_url: https://github.com/RSTZZZ/queuedWriters.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - loguru

test:
  imports:
    - queuedWriters

about:
  home: https://github.com/RSTZZZ/queuedWriters
